# Local development environment
version: '3.9'
services:
  db:
    container_name: db
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
  oss:
    container_name: oss
    image: minio/minio:RELEASE.2022-02-07T08-17-33Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: development
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
  mq:
    container_name: mq
    image: rabbitmq:3.9.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: development
    volumes:
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"
      - "15672:15672"
  imd:
    container_name: imd
    image: redis:6.2.6-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass "development"
  ms:
    container_name: ms
    image: prom/prometheus:v2.35.0
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
