version: '3.8'
services:
  db:
    container_name: db
    image: postgres:14.1
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
  oss:
    container_name: oss
    image: minio/minio:RELEASE.2022-02-07T08-17-33Z
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: development
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
  # imd:
  #   container_name: imd
  #   image: redis:6.2.6-alpine
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"