version: '3.9'
services:
  oss:
    container_name: oss
    image: minio/minio:RELEASE.2022-02-07T08-17-33Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: development
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    command: server --console-address ":9001" /data
  nginx:
    container_name: nginx
    image: nginx:1.21.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/cert
    network_mode: "host"
  mnt:
    container_name: mnt
    image: prom/prometheus:v2.34.0
    ports:
      - "9090:9090"
  mnt-gui:
    container_name: mnt-gui
    image: grafana/grafana:8.4.5
    ports:
      - "3000:3000"
