name: Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
    - name: Build
      run: |
        chmod +x gradlew
        ./gradlew build
        mv "./build/libs/forum-1.0.0.jar" "./docker/app.jar"
      
    - name: Push
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: build
        folder: docker 
        
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Deploy EC2
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SSH_HOST }}
#         username: centos
#         key: ${{ secrets.SSH_KEY }}
#         port: 22
#         script: |
#           cd ThinkMoreForum-Backend/
#           sudo docker-compose down
#           cd ..
#           rm -rf ThinkMoreForum-Backend
#           git clone -b build https://github.com/Qiming-Liu/ThinkMoreForum-Backend.git
#           cd ThinkMoreForum-Backend/
#           echo "DATETIME=$(date +'%Y-%m-%d_%H.%M.%S')" > .env
#           sudo docker-compose up -d
