name: Jacoco
on:
  push:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - uses: gradle/gradle-build-action@v2
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Jacoco
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: jacoco
          folder: build/jacocoHtml
