name: Pipeline
on:
  push:
    branches: [ main ]
jobs:
  Pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
    - name: Build
      run: |
        chmod +x gradlew
        ./gradlew build
        mv "./rabbitmq/rabbitmq.conf" "./docker/rabbitmq.conf"
        mv "./rabbitmq/definitions.json" "./docker/definitions.json"
        mv "./build/libs/forum-0.0.1.jar" "./docker/app.jar"
      
    - name: Push
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: build
        folder: docker 
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: centos
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd ThinkMoreForum-Backend/
          sudo docker-compose down
          cd ..
          rm -rf ThinkMoreForum-Backend
          git clone -b build https://github.com/Qiming-Liu/ThinkMoreForum-Backend.git
          cd ThinkMoreForum-Backend/
          echo "DATETIME=$(date +'%Y-%m-%d_%H.%M.%S')" > .env
          sudo docker-compose up -d
