name: Test
on: 
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
    - name: Test Build
      run: |
        chmod +x gradlew
        ./gradlew build
        mv "./rabbitmq/rabbitmq.conf" "./docker/rabbitmq.conf"
        mv "./rabbitmq/definitions.json" "./docker/definitions.json"
        mv "./build/libs/forum-0.0.1.jar" "./docker/app.jar"

    - name: Test Run
      run: docker-compose up -d