name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
    - name: Test
      run: |
        chmod +x gradlew
        ./gradlew test
        ./gradlew build
        mv "./build/libs/forum-1.0.0.jar" "./docker/app.jar"
        cd docker
        echo "DATETIME=$(date +'%Y-%m-%d_%H.%M.%S')" > .env
        docker-compose up -d
    
    - name: Jacoco
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: jacoco
        folder: build/jacocoHtml
